// gen-wasm-types generates TypeScript interfaces from Go WASM API annotations.
// Run via: go generate (from the wasm/ directory)
//
// Walks all directories under wasm/, parses each `package main` as a whole,
// and looks for "// @ts: <signature>" comments above registered functions.
// Outputs one .d.ts per package into ../src/@types/, mirroring the directory structure.
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

func main() {
	err := filepath.WalkDir(".", func(p string, d fs.DirEntry, err error) error {
		if err != nil || !d.IsDir() {
			return err
		}
		return processPackage(p)
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, "walk error:", err)
		os.Exit(1)
	}
}

func processPackage(dir string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi fs.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parse error: %w", err)
	}

	mainPkg, ok := pkgs["main"]
	if !ok {
		return nil // not a package main, skip
	}

	// Collect @ts: annotations and api map entries across all files in the package
	tsTypes := map[string]string{}
	type entry struct{ key, tsType string }
	var entries []entry

	for _, f := range mainPkg.Files {
		for _, decl := range f.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Doc == nil {
				continue
			}
			for _, c := range fn.Doc.List {
				text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
				if after, found := strings.CutPrefix(text, "@ts:"); found {
					tsTypes[fn.Name.Name] = strings.TrimSpace(after)
				}
			}
		}

		ast.Inspect(f, func(n ast.Node) bool {
			assign, ok := n.(*ast.AssignStmt)
			if !ok {
				return true
			}
			for i, lhs := range assign.Lhs {
				ident, ok := lhs.(*ast.Ident)
				if !ok || ident.Name != "api" || i >= len(assign.Rhs) {
					continue
				}
				composite, ok := assign.Rhs[i].(*ast.CompositeLit)
				if !ok {
					continue
				}
				for _, elt := range composite.Elts {
					kv, ok := elt.(*ast.KeyValueExpr)
					if !ok {
						continue
					}
					keyLit, ok := kv.Key.(*ast.BasicLit)
					if !ok || keyLit.Kind != token.STRING {
						continue
					}
					key := strings.Trim(keyLit.Value, `"`)
					funcName := ""
					if call, ok := kv.Value.(*ast.CallExpr); ok {
						if len(call.Args) == 1 {
							if id, ok := call.Args[0].(*ast.Ident); ok {
								funcName = id.Name
							}
						}
					}
					tsType := tsTypes[funcName]
					if tsType == "" {
						tsType = "(...args: unknown[]) => unknown"
					}
					entries = append(entries, entry{key, tsType})
				}
			}
			return true
		})
	}

	if len(entries) == 0 {
		return nil
	}

	// Derive output path and interface name from directory
	relDir, _ := filepath.Rel(".", dir)
	var outPath, interfaceName string
	if relDir == "." {
		outPath = "../src/@types/main.d.ts"
		interfaceName = "MainApi"
	} else {
		dirName := filepath.Base(relDir)
		outPath = filepath.Join("../src/@types", relDir, dirName+".d.ts")
		interfaceName = toUpperCamel(dirName) + "Api"
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		return fmt.Errorf("mkdir error: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("// Code generated by tools/gen-wasm-types. DO NOT EDIT.\n\n")
	fmt.Fprintf(&sb, "export default interface %s {\n", interfaceName)
	for _, e := range entries {
		fmt.Fprintf(&sb, "  %s: %s;\n", e.key, e.tsType)
	}
	sb.WriteString("}\n")

	if err := os.WriteFile(outPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("write error: %w", err)
	}
	fmt.Printf("wrote %s\n", outPath)
	return nil
}

func toUpperCamel(s string) string {
	var sb strings.Builder
	upper := true
	for _, r := range s {
		if r == '-' || r == '_' {
			upper = true
			continue
		}
		if upper {
			sb.WriteRune(unicode.ToUpper(r))
			upper = false
		} else {
			sb.WriteRune(r)
		}
	}
	return sb.String()
}
